#if 1
sol_mode_cmd_table DEFAULT_BINDING_TABLE = {
    .normal = {noinput,noinput,noinput,noinput,noinput,noinput,noinput,noinput,},
    .insert = {{0},{0},noinput,noinput,noinput,noinput,noinput,noinput,},
    .del    = {noinput,noinput,noinput,noinput,noinput,noinput,noinput,noinput,},
};
#else
sol_mode_cmd_table DEFAULT_BINDING_TABLE = {
    .normal = {noinput,  noinput,  noinput,noinput,noinput,noinput,noinput,noinput,},
    .insert = {textinput,textinput,noinput,noinput,noinput,noinput,noinput,noinput,},
    .del    = {noinput,  noinput,  noinput,noinput,noinput,noinput,noinput,noinput,},
};
#endif

sol_4ed_key_mapping sol_bind_table[] = {
    {}, // 4ed keys start from 1
    {.key_4ed=KeyCode_A,              .table=DEFAULT_BINDING_TABLE},
    {.key_4ed=KeyCode_B,              .table=DEFAULT_BINDING_TABLE},
    {.key_4ed=KeyCode_C,              .table=DEFAULT_BINDING_TABLE},
    {.key_4ed=KeyCode_D,              .table=DEFAULT_BINDING_TABLE},
    {.key_4ed=KeyCode_E,              .table=DEFAULT_BINDING_TABLE},
    {.key_4ed=KeyCode_F,              .table=DEFAULT_BINDING_TABLE},
    {.key_4ed=KeyCode_G,              .table=DEFAULT_BINDING_TABLE},
    {.key_4ed=KeyCode_H,              .table=DEFAULT_BINDING_TABLE},
    {.key_4ed=KeyCode_I,              .table=DEFAULT_BINDING_TABLE},
    {.key_4ed=KeyCode_J,              .table=DEFAULT_BINDING_TABLE},
    {.key_4ed=KeyCode_K,              .table=DEFAULT_BINDING_TABLE},
    {.key_4ed=KeyCode_L,              .table=DEFAULT_BINDING_TABLE},
    {.key_4ed=KeyCode_M,              .table=DEFAULT_BINDING_TABLE},
    {.key_4ed=KeyCode_N,              .table=DEFAULT_BINDING_TABLE},
    {.key_4ed=KeyCode_O,              .table=DEFAULT_BINDING_TABLE},
    {.key_4ed=KeyCode_P,              .table=DEFAULT_BINDING_TABLE},
    {.key_4ed=KeyCode_Q,              .table=DEFAULT_BINDING_TABLE},
    {.key_4ed=KeyCode_R,              .table=DEFAULT_BINDING_TABLE},
    {.key_4ed=KeyCode_S,              .table=DEFAULT_BINDING_TABLE},
    {.key_4ed=KeyCode_T,              .table=DEFAULT_BINDING_TABLE},
    {.key_4ed=KeyCode_U,              .table=DEFAULT_BINDING_TABLE},
    {.key_4ed=KeyCode_V,              .table=DEFAULT_BINDING_TABLE},
    {.key_4ed=KeyCode_W,              .table=DEFAULT_BINDING_TABLE},
    {.key_4ed=KeyCode_X,              .table=DEFAULT_BINDING_TABLE},
    {.key_4ed=KeyCode_Y,              .table=DEFAULT_BINDING_TABLE},
    {.key_4ed=KeyCode_Z,              .table=DEFAULT_BINDING_TABLE},
    {.key_4ed=KeyCode_0,              .table=DEFAULT_BINDING_TABLE},
    {.key_4ed=KeyCode_1,              .table=DEFAULT_BINDING_TABLE},
    {.key_4ed=KeyCode_2,              .table=DEFAULT_BINDING_TABLE},
    {.key_4ed=KeyCode_3,              .table=DEFAULT_BINDING_TABLE},
    {.key_4ed=KeyCode_4,              .table=DEFAULT_BINDING_TABLE},
    {.key_4ed=KeyCode_5,              .table=DEFAULT_BINDING_TABLE},
    {.key_4ed=KeyCode_6,              .table=DEFAULT_BINDING_TABLE},
    {.key_4ed=KeyCode_7,              .table=DEFAULT_BINDING_TABLE},
    {.key_4ed=KeyCode_8,              .table=DEFAULT_BINDING_TABLE},
    {.key_4ed=KeyCode_9,              .table=DEFAULT_BINDING_TABLE},
    {.key_4ed=KeyCode_Space,          .table=DEFAULT_BINDING_TABLE},
    {.key_4ed=KeyCode_Tick,           .table=DEFAULT_BINDING_TABLE},
    {.key_4ed=KeyCode_Minus,          .table=DEFAULT_BINDING_TABLE},
    {.key_4ed=KeyCode_Equal,          .table=DEFAULT_BINDING_TABLE},
    {.key_4ed=KeyCode_LeftBracket,    .table=DEFAULT_BINDING_TABLE},
    {.key_4ed=KeyCode_RightBracket,   .table=DEFAULT_BINDING_TABLE},
    {.key_4ed=KeyCode_Semicolon,      .table=DEFAULT_BINDING_TABLE},
    {.key_4ed=KeyCode_Quote,          .table=DEFAULT_BINDING_TABLE},
    {.key_4ed=KeyCode_Comma,          .table=DEFAULT_BINDING_TABLE},
    {.key_4ed=KeyCode_Period,         .table=DEFAULT_BINDING_TABLE},
    {.key_4ed=KeyCode_ForwardSlash,   .table=DEFAULT_BINDING_TABLE},
    {.key_4ed=KeyCode_BackwardSlash,  .table=DEFAULT_BINDING_TABLE},
    {.key_4ed=KeyCode_Tab,            .table=DEFAULT_BINDING_TABLE},
    {.key_4ed=KeyCode_Escape,         .table=DEFAULT_BINDING_TABLE},
    {.key_4ed=KeyCode_Pause,          .table=DEFAULT_BINDING_TABLE},
    {.key_4ed=KeyCode_Up,             .table=DEFAULT_BINDING_TABLE},
    {.key_4ed=KeyCode_Down,           .table=DEFAULT_BINDING_TABLE},
    {.key_4ed=KeyCode_Left,           .table=DEFAULT_BINDING_TABLE},
    {.key_4ed=KeyCode_Right,          .table=DEFAULT_BINDING_TABLE},
    {.key_4ed=KeyCode_Backspace,      .table=DEFAULT_BINDING_TABLE},
    {.key_4ed=KeyCode_Return,         .table=DEFAULT_BINDING_TABLE},
    {.key_4ed=KeyCode_Delete,         .table=DEFAULT_BINDING_TABLE},
    {.key_4ed=KeyCode_Insert,         .table=DEFAULT_BINDING_TABLE},
    {.key_4ed=KeyCode_Home,           .table=DEFAULT_BINDING_TABLE},
    {.key_4ed=KeyCode_End,            .table=DEFAULT_BINDING_TABLE},
    {.key_4ed=KeyCode_PageUp,         .table=DEFAULT_BINDING_TABLE},
    {.key_4ed=KeyCode_PageDown,       .table=DEFAULT_BINDING_TABLE},
    {.key_4ed=KeyCode_CapsLock,       .table=DEFAULT_BINDING_TABLE},
    {.key_4ed=KeyCode_NumLock,        .table=DEFAULT_BINDING_TABLE},
    {.key_4ed=KeyCode_ScrollLock,     .table=DEFAULT_BINDING_TABLE},
    {.key_4ed=KeyCode_Menu,           .table=DEFAULT_BINDING_TABLE},
    {.key_4ed=KeyCode_Shift,          .table=DEFAULT_BINDING_TABLE},
    {.key_4ed=KeyCode_Control,        .table=DEFAULT_BINDING_TABLE},
    {.key_4ed=KeyCode_Alt,            .table=DEFAULT_BINDING_TABLE},
    {.key_4ed=KeyCode_Command,        .table=DEFAULT_BINDING_TABLE},
    {.key_4ed=KeyCode_F1,             .table=DEFAULT_BINDING_TABLE},
    {.key_4ed=KeyCode_F2,             .table=DEFAULT_BINDING_TABLE},
    {.key_4ed=KeyCode_F3,             .table=DEFAULT_BINDING_TABLE},
    {.key_4ed=KeyCode_F4,             .table=DEFAULT_BINDING_TABLE},
    {.key_4ed=KeyCode_F5,             .table=DEFAULT_BINDING_TABLE},
    {.key_4ed=KeyCode_F6,             .table=DEFAULT_BINDING_TABLE},
    {.key_4ed=KeyCode_F7,             .table=DEFAULT_BINDING_TABLE},
    {.key_4ed=KeyCode_F8,             .table=DEFAULT_BINDING_TABLE},
    {.key_4ed=KeyCode_F9,             .table=DEFAULT_BINDING_TABLE},
    {.key_4ed=KeyCode_F10,            .table=DEFAULT_BINDING_TABLE},
    {.key_4ed=KeyCode_F11,            .table=DEFAULT_BINDING_TABLE},
    {.key_4ed=KeyCode_F12,            .table=DEFAULT_BINDING_TABLE},
};

